### ISSUE TITLE
[BUG] 파일 업로드시 500 에러

### ISSUE THREAD

**Issue by mallycrip** [Science-assignment-reps-for-student/rib-eye#3]
![image](https://user-images.githubusercontent.com/44916755/99273170-01666980-286c-11eb-9fe2-ecdcbbdc86a2.png)

**Comment by o-ozogie** [comment]
@sema0710 서버에서 로그가 안잡힙니다 ㅠㅠ

**Comment by o-ozogie** [comment]
원인은 디비 컬럼 타입 문제 expected: tinyint(1), got: bit(1)
